nav:
- week-00.md
- week-01.md
- week-02.md
- week-03.md
- week-04.md
- week-05.md
- week-06.md
- week-07.md
- week-08.md
- week-09.md
- week-10.md
- week-11.md
- week-12.md
- week-13.md
- week-14.md
- week-15.md
- week-16.md
- week-17.md
- week-18.md
- week-19.md
- week-20.md
- week-21.md
- week-22.md
- week-23.md
- week-24.md
- week-25.md
- week-26.md
